config/routes.rb
Rails.application.routes.draw do



  resources :wikis do
    resources :collaborators, only: [:create, :destroy]
  end
  resources :charges, only: [:new, :create]
  resources :user_upgrades, only: [:edit]
  resources :user_downgrades, only: [:edit]

  devise_for :users, controllers: { sessions: 'users/sessions' }

  get 'about' => 'welcome#about'

  root 'welcome#index'
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  belongs_to :user
  belongs_to :wiki
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def new
    @collaborator = Collaborator.new
  end

  def create
    @collaborator_user = User.find_by_email(params[:collaborator])
    @wiki = Wiki.find(params[:wiki_id])

    if @wiki.collaborators.exists?(user_id: @collaborator_user.id)
      flash[:notice] = "#{@collaborator_user.email} is already a collaborator."
      redirect_to edit_wiki_path(@wiki)
    else
      @collaborator = Collaborator.new(wiki_id: @wiki.id, user_id: @collaborator_user.id)
      if @collaborator.save
        flash[:notice] = "#{@collaborator_user.email} was added as a collaborator."
        redirect_to edit_wiki_path(@wiki)
      else
        flash[:alert] = "There was an error adding this collaborator. Please try again."
        redirect_to edit_wiki_path(@wiki)
      end
    end
  end

  def destroy
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = Collaborator.find(params[:id])
    @collaborator_user = User.find(@collaborator.user_id)

    if @collaborator.destroy
      flash[:notice] = "#{@collaborator_user.email} was removed as a collaborator."
      redirect_to edit_wiki_path(@wiki)
    else
      flash[:alert] = "There was an error removing this collaborator. Please try again."
      redirect_to edit_wiki_path(@wiki)
    end
  end
end







# class CollaboratorsController < ApplicationController
#   before_action :set_collaborator, only: [:show, :edit, :update, :destroy]
#
#   def index
#     @collaborators = Collaborator.all
#   end
#
#   def show
#   end
#
#   def new
#     @collaborator = Collaborator.new
#   end
#
#   def edit
#   end
#
#   def create
#     @collaborator = Collaborator.new(collaborator_params)
#
#     if @collaborator.save
#       redirect_to @collaborator, notice: 'Collaborator was successfully added.'
#     else
#       render :new
#     end
#   end
#
#   def update
#     if @collaborator.update(collaborator_params)
#       redirect_to @collaborator, notice: 'Collaborator was successfully updated.'
#     else
#       render :edit
#     end
#   end
#
#   def destroy
#     @collaborator.destroy
#     redirect_to collaborators_url, notice: 'Collaborator was successfully removed.'
#   end
#
#   private
#
#   def set_collaborator
#     @collaborator = Collaborator.find(params[:id])
#   end
#
#   def collaborator_params
#     params.require(:collaborator).permit(:user_id, :wiki_id)
#   end
# end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/views/collaborators/_form.html.erb
<div class="form-group">
  <div class="col-md-4">
  </div>
  <% if current_user.premium? || current_user.admin? %>
  <div class="col-md-8">
    <h3>Add Collaborators</h3>

    <%= form_for [@wiki, Collaborator.new] do |c| %>
      <%= email_field_tag :collaborator %>
      <%= c.submit "Add collaborator", class: 'btn btn-primary' %>
    <% end %>

    <h3>Manage Collaborators</h3>

    <% wiki.collaborators.each do |c| %>
      <% user = User.find(c.user_id) %>
      <%= user.email %>
      <%= link_to "Delete", wiki_collaborator_path(@wiki, c), class: 'btn btn-danger', method: :delete%>
    <% end %>
  </div>
  <% end %>
</div>

app/views/collaborators/edit.html.erb
<h1>Collaborators#edit</h1>
<p>Find me in app/views/collaborators/edit.html.erb</p>

app/views/collaborators/index.html.erb
<h1>Collaborators#index</h1>
<p>Find me in app/views/collaborators/index.html.erb</p>

app/views/collaborators/new.html.erb
<h1>Add New Collaborator</h1>

<%= render 'form' %>

<%= link_to 'Back', collaborators_path %>

app/views/collaborators/show.html.erb
<h1>Collaborators#show</h1>
<p>Find me in app/views/collaborators/show.html.erb</p>