config/routes.rb
Rails.application.routes.draw do



  resources :wikis do
    resources :collaborators, only: [:create, :destroy]
  end
  resources :charges, only: [:new, :create]
  resources :user_upgrades, only: [:edit]
  resources :user_downgrades, only: [:edit]

  devise_for :users, controllers: { sessions: 'users/sessions' }

  get 'about' => 'welcome#about'

  root 'welcome#index'
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user, optional: true

  default_scope { order("created_at DESC") }

  has_many :collaborators
  has_many :collaborator_users, through: :collaborators, :source => :user
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @wikis = policy_scope(Wiki)
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]
    @wiki.user = current_user

    if @wiki.save
      flash[:notice] = "You created a new wiki!"
      redirect_to [@wiki]
    else
      flash[:alert] = "There was an error when we tried to save it. Try again."
      render :new
    end
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    @wiki.assign_attributes(wiki_params)
    # @wiki.title = params[:wiki][:title]
    # @wiki.body = params[:wiki][:body]
    # @wiki.private = params[:wiki][:private]


    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the post."
      render :show
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/wikis/_form.html.erb
<%= form_for [wiki] do |f| %>
  <% if wiki.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(wiki.errors.count, "error") %>.</h4>
      <ul>
        <% wiki.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_group_tag(wiki.errors[:title]) do %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Title" %>
  <% end %>

  <%= form_group_tag(wiki.errors[:body]) do %>
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter the description of the wiki" %>
  <% end %>

  <% if current_user.admin? || current_user.premium? %>
  <div class="form-group">
    <%= f.check_box :private %> Private Wiki
  </div>
  <% end %>

  <div class="form-group">
    <%= f.submit "Save", :class => 'btn btn-success' %>
  </div>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Edit wikis with care.</p>
  </div>
  <div class="col-md-8">
    <%= render partial: "form", locals: { wiki: @wiki } %>
  </div>
</div>

<div class="col-md-8 well">
  <% if @wiki.private && (current_user.premium? || current_user.admin?) %>
  <h3>Collaborators</h3>
  <% @wiki.collaborators.each do |c| %>
    <% user = User.find(c.user_id) %>
    <%= user.email %></br>
  <% end %>
</div>
<% end %>

<div class="form-group">
  <div class="col-md-4">
  </div>
  <% if @wiki.private && (current_user.premium? || current_user.admin?) %>
  <div class="col-md-8 well">
    <h3>Add Collaborators</h3>

    <%= form_for [@wiki, Collaborator.new] do |c| %>
      <%= email_field_tag :collaborator %>
      <%= c.submit "Add Collaborator", class: 'btn btn-primary' %>
    <% end %>
    <table class="well table">
      <h3>Manage Collaborators</h3>
      <thead>
        <th>User</th>
        <th>Access</th>
      </thead>
      <tbody>
        <% @wiki.collaborators.each do |c| %>
        <tr class="media">
          <td>
            <% user = User.find(c.user_id) %>
            <%= user.email %>
          </td>
          <td>
            <%= link_to "Revoke Access", wiki_collaborator_path(@wiki, c), class: 'btn btn-danger', method: :delete%>
          <% end %>
          </td>
        </tr>
      </div>
  <% end %>
</tbody>
</table>
</div>

app/views/wikis/index.html.erb
<h1 class="text-center">Wikis</h1>

<div class="row">
  <div class="col-md-8">
    <% @wikis.each do |wiki| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to "#{wiki.title}", wiki %>
            <% if wiki.private %>
            <i class="glyphicon glyphicon-sunglasses"></i>
            <% end %>
          </h4>
        </div>
      </div>
    <% end %>
  </div>
  <br>
    <div class="col-md-4">
      <%= link_to "New Wiki", new_wiki_path, class: "btn btn-success" %>
    </div>

</div>

app/views/wikis/new.html.erb
<br>
<h1>Create a New Wiki</h1>
<div class="row">
  <div class="col-md-4">
    <p>Policies and guidelines for creating wikis are developed by the community.</p>
    <br>
    <h5>Rules</h5>
    <ul>
      <li>Everybody love everybody</li>
    </ul>
  </div>

  <div class="col-md-8">
    <%= render partial: 'form', locals: { wiki: @wiki } %>
  </div>
</div>

app/views/wikis/show.html.erb
<div>
  <h1><%= @wiki.title %></h1>
    <% if @wiki.private %>
      <i class="glyphicon glyphicon-sunglasses"></i>
      <small>Private Wiki</small>
    <% end %>
</div>
<br>

<div class="row">
  <div class="col-md-8">
    <p><%= markdown(@wiki.body).html_safe %></p>
  </div>
  <div class="col-md-4">
    <% if policy(@wiki).update? %>
      <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
    <% end %>
    <% if policy(@wiki).destroy? %>
      <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
    <% end %>
  </div>
</div>
<br>


  <% if @wiki.private && (current_user.premium? || current_user.admin?) %>
  <div class="col-md-8 well">
  <h3>List of Collaborators</h3>
  <h5><%= link_to "Edit", edit_wiki_path(@wiki) %> wiki to add or remove collaborators</h5>
  <% @wiki.collaborators.each do |c| %>
    <% user = User.find(c.user_id) %>
    <%= user.email %></br>
  <% end %>
</div>
<% end %>