config/routes.rb
Rails.application.routes.draw do



  resources :wikis do
    resources :collaborators, only: [:create, :destroy]
  end
  resources :charges, only: [:new, :create]
  resources :user_upgrades, only: [:edit]
  resources :user_downgrades, only: [:edit]

  devise_for :users, controllers: { sessions: 'users/sessions' }

  get 'about' => 'welcome#about'

  root 'welcome#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Blocipedia Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Wikis", wikis_path %></li>

        <div class="pull-right">
          <% if user_signed_in? %>
          <div class="pull-left user-info">
            <%= image_tag current_user.avatar_url(35), class: "gravatar" %>
          </div>
            <!-- Signed in as: <strong><%= current_user.email %></strong> -->
              <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
                - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
              <% else %>
                <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %> -

                <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %>
              <% end %>
        </div>
      </ul>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>

    </div>
  </body>
</html>